# sudo: required
# dist: trusty
# 
# addons:
#   apt:
#     sources:
#       - chef-stable-trusty
#     packages:
#       - chefdk
# 
# install: echo "skip bundle install"
# services: docker
# 
# env:
#   matrix:
#     - INSTANCE=default-ubuntu-1604
#     - INSTANCE=default-ubuntu-1404
#     - INSTANCE=default-ubuntu-1204
#     - INSTANCE=default-debian-8
#     - INSTANCE=default-debian-7
# 
# before_script:
#   # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
#   - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
#   - eval "$(/opt/chefdk/bin/chef shell-init bash)"
#   - /opt/chefdk/embedded/bin/chef --version
#   - /opt/chefdk/embedded/bin/cookstyle --version
#   - /opt/chefdk/embedded/bin/foodcritic --version
# 
# script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}
# 
# after_script:
#   - docker images
#   - docker ps -a
#   - cat .kitchen/logs/kitchen.log
# 
# matrix:
#   include:
#     - script:
#       - bundle install
#       - gem install cookstyle
#       - gem install foodcritic
#       - cookstyle
#       - foodcritic .
#       env: UNIT_AND_LINT=1

rvm: 2.2

sudo: required
services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 3.0.36

install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake integration:docker[${INSTANCE}]